runtime: go112

instance_class: F1
automatic_scaling:
  max_instances: 1

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /static/(.*)
  static_files: www/\1
  upload: www/(.*)

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

