steps:
  # Build the module.
  - name: 'golang'
    args: ['go', 'build', './...']
    env: ['GO111MODULE=on']
  # Test
  - name: 'golang'
    args: ['go', 'test', './...']
    env: ['GO111MODULE=on']
