steps:
  # Build
  - name: 'gcr.io/cloud-builders/bazel'
    args: ['build', '//:drawfh', '--verbose_failures']
  # Test
  - name: 'gcr.io/cloud-builders/bazel'
    args: ['test', '//...']
  # Deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    timeout: '600s'
