steps:
  # Build the module.
  - name: 'golang'
    args: ['go', 'build', './...']
    env: ['GO111MODULE=on']
  # Test
  - name: 'golang'
    args: ['go', 'test', './...']
    env: ['GO111MODULE=on']
  # Deploy - no promote
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--no-promote']
    timeout: '600s'
